// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	CORS_ORIGIN: "https://newshaberglobal.vercel.app,https://newshaberglobal.com,https://www.newshaberglobal.com";
	VAPID_SUBJECT: "mailto:admin@newsplatform.com";
	GMAIL_FROM_EMAIL: "newshaberglobal@gmail.com";
	JWT_SECRET: string;
	VAPID_PUBLIC_KEY: string;
	VAPID_PRIVATE_KEY: string;
	CRON_SECRET: string;
	R2: R2Bucket;
	DB: D1Database;
}
