name = "news-v2-api"
main = "src/index.ts"
compatibility_date = "2024-06-14"
compatibility_flags = ["nodejs_compat"]
account_id = "dce222617f90501d5b84b15117640be0"

[[d1_databases]]
binding = "DB"
database_name = "news-platform-db"
database_id = "ba28088d-824f-4648-b88b-f532af4f464c"

[vars]
JWT_SECRET = "h0eZQQvB7mKx9NpL2oR5sT8uW1yZ4aC3dF6gI0jM3nPqRtUwXzAeHkNpQrStUvWxYz01234o58="
CORS_ORIGIN = "*"
VAPID_PUBLIC_KEY = "BJw-hAa4p86NtwMCwH0cbGdVYouRKaok1VTKXVj63jqrzElSTwJOzg7r8kcRHEo6CIS0VyFOzrUsx15GuLewroI"
VAPID_PRIVATE_KEY = "uSzixBjdjkrtEiccFpaHIgNfhYnLHMwYf9o7CdKGA-E"
VAPID_SUBJECT = "mailto:admin@newsplatform.com"
SMTP_RELAY_URL = "https://healing-caused-cgi-folder.trycloudflare.com/send"
SMTP_RELAY_SECRET = "news-haber-global-2026-secret"

[triggers]
crons = ["*/5 * * * *"]
