INSERT OR IGNORE INTO users (email, password_hash, name, role)
VALUES ('admin@newsplatform.com', '9d8a0a27e6591a592b088582152ab808:676ef1cf9f6b5b3e3422361dc20c66f53ff6db11d1fcb974212d720206e6f050', 'Admin User', 'admin');

INSERT OR IGNORE INTO categories (name, slug, description, color, sort_order) VALUES
    ('Technology', 'technology', 'Latest in tech, AI, and innovation', '#3b82f6', 1),
    ('World News', 'world-news', 'Breaking stories from around the globe', '#ef4444', 2),
    ('Economy', 'economy', 'Markets, business, and financial news', '#10b981', 3),
    ('Sports', 'sports', 'Scores, analysis, and sports coverage', '#f59e0b', 4),
    ('Science', 'science', 'Discoveries, research, and breakthroughs', '#8b5cf6', 5),
    ('Health', 'health', 'Wellness, medicine, and public health', '#ec4899', 6),
    ('Entertainment', 'entertainment', 'Culture, movies, music, and celebrities', '#f97316', 7),
    ('Politics', 'politics', 'Government, policy, and political analysis', '#6366f1', 8);

INSERT OR IGNORE INTO news (title, slug, excerpt, content, image_url, image_alt, category_id, author_id, status, is_featured, is_breaking, seo_title, seo_description, published_at) VALUES
('OpenAI Unveils GPT-5: A New Era of Artificial Intelligence', 'openai-unveils-gpt-5-new-era-ai',
'OpenAI has announced the release of GPT-5, their most advanced language model yet.',
'<h2>A Quantum Leap in AI</h2><p>OpenAI has officially unveiled GPT-5, featuring remarkable improvements across all benchmarks.</p><ul><li>40% improvement on mathematical benchmarks</li><li>Native multimodal support</li><li>2x faster inference</li></ul>',
'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=1200',
'AI Technology Concept',
1, 1, 'published', 1, 1,
'GPT-5 Released: OpenAI Launches Most Advanced AI Model Yet',
'OpenAI unveils GPT-5 with unprecedented reasoning, 1M token context, and native multimodal capabilities.',
'2025-01-15 09:00:00'),

('Global Climate Summit Reaches Historic Agreement on Emissions', 'global-climate-summit-historic-agreement',
'World leaders have reached a landmark agreement, committing to 60% emission reductions by 2035.',
'<h2>A Turning Point for Climate Action</h2><p>Over 190 nations have committed to reducing greenhouse gas emissions by 60% from 2005 levels by 2035.</p><ul><li>60% reduction by 2035</li><li>$500 billion climate finance package</li><li>80% clean electricity by 2030</li></ul>',
'https://images.unsplash.com/photo-1569163139394-de4e4f3f5fd7?w=1200',
'Climate Summit Meeting',
2, 1, 'published', 1, 0,
'Historic Climate Agreement: 190 Nations Commit to 60% Emission Cuts',
'World leaders reach landmark climate agreement with binding 60% emission reduction targets.',
'2025-01-14 14:30:00'),

('Federal Reserve Signals Multiple Rate Cuts in 2025', 'federal-reserve-signals-rate-cuts-2025',
'The Federal Reserve has indicated it may implement up to four interest rate cuts in 2025.',
'<h2>Dovish Shift in Monetary Policy</h2><p>Federal Reserve Chair Jerome Powell signaled a significant shift in monetary policy.</p><ul><li>S&P 500: +2.3% to new all-time high</li><li>NASDAQ: +3.1%</li><li>10-Year Treasury: Dropped to 3.78%</li></ul>',
'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=1200',
'Stock Market Charts',
3, 1, 'published', 0, 0,
'Fed Signals 4 Rate Cuts in 2025: Markets Surge to Record Highs',
'Federal Reserve indicates multiple rate cuts coming in 2025 as inflation cools.',
'2025-01-13 16:00:00'),

('Liverpool Extends Premier League Lead with Dominant Derby Win', 'liverpool-extends-premier-league-lead-derby',
'Liverpool secured a commanding 3-0 victory over Everton in the Merseyside derby.',
'<h2>Reds Dominate Merseyside</h2><p>Liverpool produced a masterclass performance at Anfield, dismantling Everton 3-0.</p><ul><li>23 min - Mohamed Salah</li><li>41 min - Darwin Nunez</li><li>87 min - Cody Gakpo</li></ul>',
'https://images.unsplash.com/photo-1522778119026-d647f0596c20?w=1200',
'Football Stadium',
4, 1, 'published', 0, 0,
'Liverpool 3-0 Everton: Reds Extend Premier League Lead',
'Liverpool dominate Merseyside derby with goals from Salah, Nunez, and Gakpo.',
'2025-01-12 20:00:00'),

('NASA Confirms Water Ice Discovery on Mars Surface', 'nasa-confirms-water-ice-mars-surface',
'NASA scientists have confirmed the discovery of accessible water ice deposits on the Martian surface.',
'<h2>Water on Mars: Confirmed</h2><p>NASA Mars Reconnaissance Orbiter has confirmed significant water ice deposits near the Martian equator.</p><ul><li>Multiple sites near equator</li><li>As shallow as 1 meter below surface</li><li>10,000+ cubic meters per site</li></ul>',
'https://images.unsplash.com/photo-1614728263952-84ea256f9679?w=1200',
'Mars Surface',
5, 1, 'published', 0, 0,
'NASA Confirms Water Ice on Mars: Breakthrough for Colonization',
'NASA confirms accessible water ice deposits on Mars surface near equator.',
'2025-01-11 11:00:00'),

('Breakthrough Cancer Vaccine Shows 90% Efficacy in Clinical Trials', 'breakthrough-cancer-vaccine-90-percent-efficacy',
'A new mRNA-based cancer vaccine has shown remarkable 90% efficacy in clinical trials.',
'<h2>Revolutionary Cancer Prevention</h2><p>Moderna personalized mRNA cancer vaccine achieved 90% efficacy in preventing melanoma recurrence.</p><ul><li>90% reduction in cancer recurrence</li><li>6,500 participants across 200 sites</li><li>3-year follow-up data</li></ul>',
'https://images.unsplash.com/photo-1579165466741-7f35e4755660?w=1200',
'Medical Research',
6, 1, 'published', 0, 0,
'Cancer Vaccine 90% Effective: mRNA Breakdown in Clinical Trials',
'Moderna mRNA cancer vaccine shows 90% efficacy preventing melanoma recurrence.',
'2025-01-10 08:00:00'),

('Bitcoin Surges Past $120,000 as Institutional Adoption Accelerates', 'bitcoin-surges-past-120000-institutional-adoption',
'Bitcoin has reached an all-time high above $120,000 as major financial institutions embrace cryptocurrency.',
'<h2>Crypto Goes Mainstream</h2><p>Bitcoin has shattered its previous all-time high, surging past $120,000.</p><ul><li>$50B+ in ETF inflows</li><li>Fortune 500 companies adding BTC</li><li>Supply reduction impact continuing</li></ul>',
'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=1200',
'Bitcoin Cryptocurrency',
3, 1, 'published', 0, 1,
'Bitcoin Price Surpasses $120K: Institutional Crypto Adoption Soars',
'Bitcoin reaches new all-time high above $120,000 driven by institutional adoption.',
'2025-01-09 12:00:00'),

('Apple Vision Pro 2 Announced with Revolutionary Spatial Computing', 'apple-vision-pro-2-spatial-computing',
'Apple has unveiled the second generation of its mixed reality headset.',
'<h2>The Future of Computing</h2><p>Apple Vision Pro 2 features micro-OLED displays with 8K resolution per eye.</p><ul><li>8K micro-OLED per eye</li><li>120 degrees FOV</li><li>350g weight (50% lighter)</li><li>$2,499 price</li></ul>',
'https://images.unsplash.com/photo-1622979135225-d2ba269cf1ac?w=1200',
'VR Headset Technology',
1, 1, 'published', 0, 0,
'Apple Vision Pro 2: 8K Display, Half the Weight, $2,499',
'Apple unveils Vision Pro 2 with 8K micro-OLED displays, 120 degree FOV, and $2,499 price.',
'2025-01-08 19:00:00'),

('EU Passes Comprehensive AI Regulation Framework', 'eu-passes-ai-regulation-framework',
'The European Union has passed the worlds most comprehensive AI regulation.',
'<h2>EU Leads on AI Governance</h2><p>The European Parliament voted overwhelmingly in favor of the AI Act.</p><ul><li>Unacceptable Risk: Banned</li><li>High Risk: Strict requirements</li><li>Limited Risk: Transparency requirements</li><li>Minimal Risk: No restrictions</li></ul>',
'https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?w=1200',
'EU Parliament',
8, 1, 'published', 0, 0,
'EU AI Act: Worlds Most Comprehensive AI Regulation Passed',
'European Union passes landmark AI Act establishing risk-based framework for AI governance.',
'2025-01-07 15:00:00'),

('Oscar Nominations Announced: Sci-Fi Epic Leads with 12 Nods', 'oscar-nominations-sci-fi-epic-12-nods',
'This years Oscar nominations have been announced, with sci-fi epic Stellar Horizons leading with 12 nominations.',
'<h2>Awards Season Heats Up</h2><p>Stellar Horizons dominates with 12 nominations including Best Picture and Best Director.</p><ul><li>Stellar Horizons - 12 nominations</li><li>The Last Letter - 9 nominations</li><li>Breaking Ground - 8 nominations</li></ul>',
'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=1200',
'Cinema Theater',
7, 1, 'published', 0, 0,
'Oscars 2025: Sci-Fi Epic Stellar Horizons Leads with 12 Nominations',
'Stellar Horizons leads Oscar nominations with 12 nods including Best Picture and Best Director.',
'2025-01-06 10:00:00');

INSERT OR IGNORE INTO tags (name, slug) VALUES
    ('AI', 'ai'),
    ('Climate', 'climate'),
    ('Finance', 'finance'),
    ('Football', 'football'),
    ('NASA', 'nasa'),
    ('Medical', 'medical'),
    ('Apple', 'apple'),
    ('EU', 'eu'),
    ('Oscars', 'oscars'),
    ('Bitcoin', 'bitcoin');

INSERT OR IGNORE INTO news_tags (news_id, tag_id) VALUES
    (1, 1),
    (2, 2),
    (3, 3),
    (4, 4),
    (5, 5),
    (6, 6),
    (7, 10),
    (7, 3),
    (8, 7),
    (9, 8),
    (9, 1),
    (10, 9);
